//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "us-west-2_Pu0p70AJg"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "2eiegjvup4961tp33hghnsoo4u"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .USWest2

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "157fbsh7nbklckeqhc0gqo1unmp91kgpnvkphn3kffl290pnal36"
