//
//  Layers.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//

import Foundation
import UIKit
import AWSDynamoDB

class Layers: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _venueName: String?
    var _layerName: String?
    
    class func dynamoDBTableName() -> String {

        return "hackathon-mobilehub-193603921-layers"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_venueName"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_venueName" : "venueName",
               "_layerName" : "layerName",
        ]
    }
}
