//
//  MasterVenue.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//

import Foundation
import UIKit
import AWSDynamoDB

class MasterVenue: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _qRCode: String?
    var _imageHeight: NSNumber?
    var _imageWidth: NSNumber?
    var _timestamp: String?
    var _userId: String?
    var _venueName: String?
    
    class func dynamoDBTableName() -> String {

        return "hackathon-mobilehub-193603921-master-venue"
    }
    
    class func hashKeyAttribute() -> String {

        return "_qRCode"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_qRCode" : "QRCode",
               "_imageHeight" : "imageHeight",
               "_imageWidth" : "imageWidth",
               "_timestamp" : "timestamp",
               "_userId" : "userId",
               "_venueName" : "venueName",
        ]
    }
}
