//
//  TextPosts.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//

import Foundation
import UIKit
import AWSDynamoDB

class TextPosts: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _qRCode: String?
    var _body: String?
    var _title: String?
    
    class func dynamoDBTableName() -> String {

        return "hackathon-mobilehub-193603921-text-posts"
    }
    
    class func hashKeyAttribute() -> String {

        return "_qRCode"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_qRCode" : "QRCode",
               "_body" : "body",
               "_title" : "title",
        ]
    }
}
